"""
Django settings for instrument_history_api project.

Generated by 'django-admin startproject' using Django 1.10.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os
from urllib.parse import unquote

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = NotImplementedError('SECRET_KEY must be overridden')



# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG')

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '[::1]']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'instrument_history_api.api_app',
    'rest_framework',

]

REST_FRAMEWORK = {
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'instrument_history_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'instrument_history_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(os.environ.get('DATABASE_DIR', BASE_DIR), 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = NotImplementedError('STATIC_ROOT should be overridden')


# APP CONFIG
#

# Seligson URLs grabbed from https://github.com/nnarhinen/SeligsonRahastoarvot/blob/master/res/values/strings.xml
_INSTRUMENT_URL_TO_NAME = {
    'http://www.morningstar.fi/fi/funds/snapshot/snapshot.aspx?id=F0GBR04UMF': 'Seligson & Co Global Top 25 Pharmaceuticals A',
    'http://www.seligson.fi/graafit/global-pharma.csv': 'Seligson & Co Global Top 25 Pharmaceuticals A',
    'http://www.morningstar.fi/fi/funds/snapshot/snapshot.aspx?id=F0GBR04O2R': 'Seligson & Co Global Top 25 Brands Fund (A)',
    'http://www.seligson.fi/graafit/global-brands.csv': 'Seligson & Co Global Top 25 Brands Fund (A)',
    'http://www.morningstar.fi/fi/funds/snapshot/snapshot.aspx?id=F0GBR04O2J': 'Seligson & Co Rahamarkkinarahasto AAA A',
    'http://www.seligson.fi/graafit/rahamarkkina.csv': 'Seligson & Co Rahamarkkinarahasto AAA A',
    'http://www.morningstar.fi/fi/funds/snapshot/snapshot.aspx?id=F0GBR04OGI': 'FIM Euro',
    'http://www.morningstar.fi/fi/funds/snapshot/snapshot.aspx?id=0P0000GGNP': 'SKAGEN Kon-Tiki A (EUR)',
    'http://www.morningstar.fi/fi/funds/snapshot/snapshot.aspx?id=F00000UF2B': 'Handelsbanken Euro Obligaatio (A1 EUR)',
    'http://www.morningstar.fi/fi/etf/snapshot/snapshot.aspx?id=0P0000M7ZP': 'Saksa db x-trackers DAX UCITS ETF EUR DBXD F Kasvu',
    'http://www.morningstar.fi/fi/etf/snapshot/snapshot.aspx?id=0P0000RTOH': 'Aasia ilman Japania iShares Core MSCI Pacific ex Japan UCITS ETF EUR SXR1 F Kasvu',
    'http://www.morningstar.fi/fi/etf/snapshot/snapshot.aspx?id=0P0000MEI0': 'iShares Core MSCI World UCITS ETF',
    'http://www.morningstar.fi/fi/funds/snapshot/snapshot.aspx?id=F00000TH8W': 'Nordnet Superrahasto Suomi',
    'http://www.morningstar.fi/fi/etf/snapshot/snapshot.aspx?id=0P0000HNXD': 'db x-trackers Euro Stoxx 50 UCITS ETF (DR) 1C (EUR) DXET',
    'http://tools.morningstar.fi/fi/stockreport/default.aspx?SecurityToken=0P0000A5Z8]3]0]E0WWE$$ALL': 'KONE Corporation',
    'http://www.morningstar.fi/fi/etf/snapshot/snapshot.aspx?id=0P0000Y5NI': 'db x-trackers Nikkei 225 UCITS ETF (DR) 1D (EUR) XDJP (Frankfurt)'
}

SELIGSON_URLS = [url for url in _INSTRUMENT_URL_TO_NAME if 'seligson' in url]


def GET_INSTRUMENT_NAME(encoded_url):
    return _INSTRUMENT_URL_TO_NAME[unquote(encoded_url)]


def HAS_INSTRUMENT_URL(encoded_url):
    try:
        GET_INSTRUMENT_NAME(encoded_url)
        return True
    except KeyError:
        return False


#
WARC_FOLDER = NotImplementedError('WARC_FOLDER should be overridden')
